config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'clients#index', as: 'clients'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'clients/new', to: 'clients#new', as: 'new_client'
  post '/', to: 'clients#create'
  get 'clients/:id', to: 'clients#show', as: 'show_client'  
  post 'clients', to: 'client#create'
  get 'clients/:client_id/cars', to: 'cars#client_cars', as: 'cars'
  get 'clients/:client_id/cars/new', to: 'cars#new', as: 'new_car'
  post 'clients/:client_id/cars', to: 'cars#create'
  get 'clients/:client_id/cars/:id', to: 'cars#show', as: 'show_car'
  get 'clients/:client_id/cars/:car_id/visits/:id', to: 'visits#show', as: 'show_visit'
  get 'clients/:client_id/cars/:car_id/visits/:visit_id/services/:id', to: 'services#show', as: 'show_service'
  get 'workers', to: 'workers#index'
  get 'workers/:id', to:'workers#show', as: 'show_worker'
  get 'client/:encrypt', to:'clients#pavyko'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :client
  has_many :visits


  BODY_TYPES = [['Sedanas', 'Saloon'], 
                ['Universalas', 'Estate'], 
                ['Kabrioletas', 'Cabriolet'], 
                ['Visureigis', 'Off_road'], 
                ['Kupė', 'Coupe'],
                ['Vienatūris', 'Van'],
                ['Kita', 'Other']]
  FUEL_TYPES = [['Benzinas', 'Petrol'], 
                ['Dyzelis', 'Diesel'], 
                ['Benzinas/Dujos', 'LPG'], 
                ['Hibridas', 'Hybrid'], 
                ['ELektra', 'Electric'],
                ['Vandenilis', 'Hydrogen'],
                ['Etanolis', 'Ethanol'],
                ['Kita', 'Other']]
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :cars
  has_many :visits, :through => :cars
  
  has_secure_password

end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :service
end

app/models/repair_status.rb
class RepairStatus < ApplicationRecord
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :repair_statuses
  belongs_to :worker
  belongs_to :visit
  has_many :works
  has_many :parts

  def sum_parts_price
    sum = 0
    parts.each do |part|
      sum += part.quantity * part.price
    end
    sum
  end

  def sum_works_price
    sum = 0
    works.each do |work|
      sum += work.quantity * work.price
    end
    sum
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :client
  belongs_to :car
  has_many :visit_statuses
  has_many :services
end

app/models/visit_status.rb
class VisitStatus < ApplicationRecord
  belongs_to :visit
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :service
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :services
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def client_cars
    @cars = Car.where(client_id: params[:client_id])
  end

  def show
    @car = Car.find(params[:id])
    @visits = @car.visits
  end

  def new    
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.client_id = params[:client_id]
    if @car.save
      redirect_to clients_path
    else
      render :new
    end
  end


  private

  def car_params
    params.require(:car).permit(:make,
                                :model,
                                :production_year,
                                :license_plate,
                                :vin_code,
                                :body_type,
                                :cubic_capacity,
                                :power,
                                :fuel,
                                :color,
                                :ta_date)
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def show 
    @visit = Visit.find(params[:id])
    @services = @visit.services
    
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController

  def index
    @workers = Worker.all
  end

  def show
    @worker = Worker.find(params[:id])
    @services = @worker.services
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/workers/index.html.erb
<div class="container">
<h2><%= link_to "Klientai", clients_path %>    <%= link_to "Darbuotojai", workers_path %></h2>
  <table class="table table-responsive table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Surname</th>
        <th>Position</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @workers.each do |worker| %>
        <tr>
          <td><%= worker.id %></td>
          <td><%= worker.name %></td>
          <td><%= worker.surname %></td>
          <td><%= worker.position %></td>
          <td><%= worker.email %></td>
          <td><%= link_to "View", show_worker_path(worker), class: "btn btn-default" %></td>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/workers/show.html.erb
<div class="container">
  <h2><%= link_to "Klientai", clients_path %> /
   
  </h2>
  <table class="table table-responsive table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= service.created_at %></td>
        <td><%= link_to "View", show_service_path(service.visit.car.client, service.visit.car, service.visit, service), class: "btn btn-default" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>