config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'clients#index', as: 'clients'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'clients/new', to: 'clients#new', as: 'new_client'
  post '/', to: 'clients#create'
  get 'clients/:id', to: 'clients#show', as: 'show_client'  
  post 'clients', to: 'client#create'
  get 'clients/:client_id/cars', to: 'cars#client_cars', as: 'cars'
  get 'clients/:client_id/cars/new', to: 'cars#new', as: 'new_car'
  post 'clients/:client_id/cars', to: 'cars#create'
  get 'clients/:client_id/cars/:id', to: 'cars#show', as: 'show_car'
  get 'clients/:client_id/cars/:car_id/visits/:id', to: 'visits#show', as: 'show_visit'
  get 'clients/:client_id/cars/:car_id/visits/:visit_id/services/:id', to: 'services#show', as: 'show_service'
  get 'workers', to: 'workers#index'
  get 'workers/:id', to:'workers#show', as: 'show_worker'
  get 'client/:encrypt', to:'clients#pavyko'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :client
  has_many :visits


  BODY_TYPES = [['Sedanas', 'Saloon'], 
                ['Universalas', 'Estate'], 
                ['Kabrioletas', 'Cabriolet'], 
                ['Visureigis', 'Off_road'], 
                ['Kupė', 'Coupe'],
                ['Vienatūris', 'Van'],
                ['Kita', 'Other']]
  FUEL_TYPES = [['Benzinas', 'Petrol'], 
                ['Dyzelis', 'Diesel'], 
                ['Benzinas/Dujos', 'LPG'], 
                ['Hibridas', 'Hybrid'], 
                ['ELektra', 'Electric'],
                ['Vandenilis', 'Hydrogen'],
                ['Etanolis', 'Ethanol'],
                ['Kita', 'Other']]
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :cars
  has_many :visits, :through => :cars
  
  has_secure_password

end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :service
end

app/models/repair_status.rb
class RepairStatus < ApplicationRecord
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :repair_statuses
  belongs_to :worker
  belongs_to :visit
  has_many :works
  has_many :parts

  def sum_parts_price
    sum = 0
    parts.each do |part|
      sum += part.quantity * part.price
    end
    sum
  end

  def sum_works_price
    sum = 0
    works.each do |work|
      sum += work.quantity * work.price
    end
    sum
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :client
  belongs_to :car
  has_many :visit_statuses
  has_many :services
end

app/models/visit_status.rb
class VisitStatus < ApplicationRecord
  belongs_to :visit
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :service
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :services
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def client_cars
    @cars = Car.where(client_id: params[:client_id])
  end

  def show
    @car = Car.find(params[:id])
    @visits = @car.visits
  end

  def new    
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.client_id = params[:client_id]
    if @car.save
      redirect_to clients_path
    else
      render :new
    end
  end


  private

  def car_params
    params.require(:car).permit(:make,
                                :model,
                                :production_year,
                                :license_plate,
                                :vin_code,
                                :body_type,
                                :cubic_capacity,
                                :power,
                                :fuel,
                                :color,
                                :ta_date)
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def show 
    @visit = Visit.find(params[:id])
    @services = @visit.services
    
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/visit_statuses_helper.rb
module VisitStatusesHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/cars/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 center-block">
      <div class="panel-heading">
        <div class="panel-title text-center">
          <h1 class="title">Naujas automobilis</h1>
          <hr />
        </div>
        


<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">Markė</label>
    <div class="">
      <%= f.text_field :make, placeholder: "Markė", class: "form-control" %>
    </div>
  </div>

    <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">Modelis</label>
    <div class="">
      <%= f.text_field :model, placeholder: "Modelis", class: "form-control" %>
    </div>
  </div>

   <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">Pagaminimo metai</label>
    <div class="">
      <%= f.text_field :production_year, placeholder: "Pagaminimo metai", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">Valstybinis numeris</label>
    <div class="">
      <%= f.text_field :license_plate, placeholder: "Valstybinis numeris", class: "form-control" %>
    </div>
  </div>

    <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">Kėbulo numeris</label>
    <div class="">
      <%= f.text_field :vin_code, placeholder: "Kėbulo numeris", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">Kėbulo tipas</label>
    <div class="">
      <%= f.select :body_type, Car::BODY_TYPES, { selected: @car.try(:body_type) || 'Sedanas'}, { class: "form-control" }  %>
    </div>
  </div>

  <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">Darbinis tūris, cm<sup>3</sup></label>
    <div class="">
      <%= f.text_field :cubic_capacity, placeholder: "Darbinis tūris", class: "form-control" %>
    </div>
  </div>

    <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">Galia, KW</label>
    <div class="">
      <%= f.text_field :power, placeholder: "Galia", class: "form-control" %>
    </div>
  </div>

    <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">Kuro tipas</label>
    <div class="">
      <%= f.select :fuel, Car::FUEL_TYPES, { selected: @car.try(:fuel) || 'Benzinas'}, { class: "form-control" }  %>
    </div>
  </div>

  <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">Spalva</label>
    <div class="">
      <%= f.text_field :color, placeholder: "Spalva", class: "form-control" %>
    </div>
  </div>

   <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">TA Data</label>
    <div class="">
      <%= f.text_field :ta_date, placeholder: "TA data", class: "form-control" %>
    </div>
  </div>


  <div class="actions">
    <%= f.submit 'Saugoti', class: "btn btn-success btn-lg btn-block login-button" %>
  </div>
<% end %>

  <br />

          <%= link_to 'Atgal', clients_path, class: "btn btn-primary" %> 
      </div>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container">
  <h2><%= link_to "Klientai", clients_path %> /
      <%= link_to "#{@car.client.name} #{@car.client.surname}", show_client_path(@car.client) %> /
      <%= link_to "#{@car.make} #{@car.model} #{@car.license_plate}", show_car_path(@car.client, @car) %>  
  </h2>
  <table class="table table-responsive table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>End Date</th>
        <th>Return</th>
        <th>Mileage</th>
        <th>Current Status</th>
      </tr>
    </thead>
    <tbody>
      <% @visits.each do |visit| %>
        <tr>
          <td><%= visit.id %></td>
          <td><%= visit.name %></td>
          <td><%= visit.end_date %></td>
          <td><%= visit.return_date %></td>
          <td><%= visit.mileage %></td>
          <td><%= visit.visit_statuses.last.name %></td>
          <td><%= link_to "Services", show_visit_path(visit.car.client, visit.car, visit), class: "btn btn-default" %></td>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/visits/show.html.erb
<div class="container">
  <h2><%= link_to "Klientai", clients_path %> /
      <%= link_to "#{@visit.car.client.name} #{@visit.car.client.surname}", show_client_path(@visit.car.client) %> /
      <%= link_to "#{@visit.car.make} #{@visit.car.model} #{@visit.car.license_plate}", show_car_path(@visit.car.client, @visit.car) %> /
      <%= link_to @visit.created_at.to_date, show_visit_path(@visit.client, @visit.car, @visit) %>
  </h2>
  <table class="table table-responsive table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Description</th>
        <th>Worker</th>
        <th>Current Status</th>
      </tr>
    </thead>
    <tbody>
      <% @services.each do |service| %>
        <tr>
          <td><%= service.id %></td>
          <td><%= service.name %></td>
          <td><%= service.description %></td>
          <td><%= "#{service.worker.name} #{service.worker.surname}"  %></td>
          <td><%= service.repair_statuses.last.name %></td>
          <td><%= link_to "View", show_service_path(service.visit.car.client, service.visit.car, service.visit, service), class: "btn btn-default" %></td>
          
        </tr>
        <% end %>
    </tbody>
  </table>
</div>