config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'clients#index', as: 'clients'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'clients/new', to: 'clients#new', as: 'new_client'
  post '/', to: 'clients#create'
  get 'clients/:id', to: 'clients#show', as: 'show_client'  
  post 'clients', to: 'client#create'
  get 'clients/:client_id/cars', to: 'cars#client_cars', as: 'cars'
  get 'clients/:client_id/cars/new', to: 'cars#new', as: 'new_car'
  post 'clients/:client_id/cars', to: 'cars#create'
  get 'clients/:client_id/cars/:id', to: 'cars#show', as: 'show_car'
  get 'clients/:client_id/cars/:car_id/visits/:id', to: 'visits#show', as: 'show_visit'
  get 'clients/:client_id/cars/:car_id/visits/:visit_id/services/:id', to: 'services#show', as: 'show_service'
  get 'workers', to: 'workers#index'
  get 'workers/:id', to:'workers#show', as: 'show_worker'
  get 'client/:encrypt', to:'clients#pavyko'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :client
  has_many :visits


  BODY_TYPES = [['Sedanas', 'Saloon'], 
                ['Universalas', 'Estate'], 
                ['Kabrioletas', 'Cabriolet'], 
                ['Visureigis', 'Off_road'], 
                ['Kupė', 'Coupe'],
                ['Vienatūris', 'Van'],
                ['Kita', 'Other']]
  FUEL_TYPES = [['Benzinas', 'Petrol'], 
                ['Dyzelis', 'Diesel'], 
                ['Benzinas/Dujos', 'LPG'], 
                ['Hibridas', 'Hybrid'], 
                ['ELektra', 'Electric'],
                ['Vandenilis', 'Hydrogen'],
                ['Etanolis', 'Ethanol'],
                ['Kita', 'Other']]
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :cars
  has_many :visits, :through => :cars
  
  has_secure_password

end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :service
end

app/models/repair_status.rb
class RepairStatus < ApplicationRecord
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :repair_statuses
  belongs_to :worker
  belongs_to :visit
  has_many :works
  has_many :parts

  def sum_parts_price
    sum = 0
    parts.each do |part|
      sum += part.quantity * part.price
    end
    sum
  end

  def sum_works_price
    sum = 0
    works.each do |work|
      sum += work.quantity * work.price
    end
    sum
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :client
  belongs_to :car
  has_many :visit_statuses
  has_many :services
end

app/models/visit_status.rb
class VisitStatus < ApplicationRecord
  belongs_to :visit
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :service
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :services
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def client_cars
    @cars = Car.where(client_id: params[:client_id])
  end

  def show
    @car = Car.find(params[:id])
    @visits = @car.visits
  end

  def new    
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.client_id = params[:client_id]
    if @car.save
      redirect_to clients_path
    else
      render :new
    end
  end


  private

  def car_params
    params.require(:car).permit(:make,
                                :model,
                                :production_year,
                                :license_plate,
                                :vin_code,
                                :body_type,
                                :cubic_capacity,
                                :power,
                                :fuel,
                                :color,
                                :ta_date)
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AutoRemontas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href=<%=clients_path%>>Klientai <span class="sr-only">(current)</span></a></li>
            <li><a href=<%=workers_path%>>Darbuotojai</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <p class="navbar-btn"><%= link_to 'Prisijungti', login_path, class: 'btn btn-default' %></p>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
      <%= yield %>
  </body>
</html>